# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  ğŸ¤ Thanks for opening this pull request! Please check out our contributing guidelines [here](https://github.com/Magic-Academy/.github/blob/main/CODE_OF_CONDUCT.md)

newIssueWelcomeComment: >
  ğŸ¤ Thanks for opening this issue, a maintainer will get back to you shortly!